# Generated by Django 3.1.7 on 2021-06-28 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.CharField(blank=True, max_length=128, verbose_name='Organization')),
                ('telephone', models.CharField(blank=True, max_length=50, verbose_name='Telephone')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
        migrations.CreateModel(
            name='ExperimentInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('purpose', models.CharField(max_length=20)),
                ('agentNumber', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=users.models.upload_path)),
                ('result', models.FilePathField(path=users.models.download_path)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MyExperiment', to='users.userprofile')),
            ],
        ),
    ]
