# Generated by Django 3.1.7 on 2021-06-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentinfo',
            name='user',
        ),
        migrations.AddField(
            model_name='experimentinfo',
            name='user_id',
            field=models.CharField(default='114514', max_length=20),
        ),
    ]
